---
title: "CW_cattle-impacts_analysis"
output: html_document
date: "2026-04-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

## Reading in Data


```{r cars}
Cattle_Impact_Full <- read.csv("Cleaned_Capstone_Data.csv") %>% # reading in csv
  rename(  # cleaning up and simplifying column names
    Plot = Plot._Number,
    Watershed = Subwatrshed_Location, 
    HGM = Hydrogeomorphic_Classification
  ) %>%
  mutate(  # Editing data in our columns for cleaning (use with caution!)
    Watershed = str_trim(Watershed), # remove whitespace from Watershed column
    Closest_Water_Distance = as.numeric(Closest_Water_Distance), # formatting Closest_Water_Distance column as a number
    Date = as.Date(Date, format = "%m/%d/%Y") # Reformats the Date column into a format which R can interpret as dates correctly
  ) %>%
  filter(!is.na(Plot)) # removing one blank row


Cattle_Impact <- Cattle_Impact_Full  %>%
  select(Date, Plot, Watershed, HGM, Percent_Canopy:Manure_Count, 
         Closest_Water_Distance, Water_Type, Restoration_Location,
         Stream_Restoration_Type:Cattle_Trail_Crossing_or_Bedding_Area) %>%  # selecting relevant columns
  mutate(
    Restoration_Location_2 = case_when(
      Restoration_Location %in% c("Both", "Inside", "Downstream") ~ "in_or_downstream", 
      TRUE ~ "none_or_upstream"),
    
    HGM = str_trim(HGM),
    
    HGM_2 = case_when(
      HGM %in% c("Riparian_Mid_Gradient", "Riparian_High_Gradient") ~ "Riparian",
      HGM %in% c("Subsurface_Low_Gradient", "Subsurface_Mid_Gradient", "Subsurface_High_Gradient") ~ "Subsurface",
      TRUE ~ HGM),
    
    Hoof_Punch_Present = case_when(
      Percent_Hoof_Punch > 0 ~ "yes",
      TRUE ~ "no")
    )

```

## Comparing early visit to late visit

*TODO: there's at least one row where the date is NA*

```{r repeat-timing, echo=FALSE}

# filtering to repeated plots
late_plots <- Cattle_Impact_Full %>%
  filter(Date > "2025-09-01") %>%
  pull(Plot)

Cattle_Impact_Repeat <- Cattle_Impact %>%
  filter(Plot %in% late_plots) %>%
  mutate(
    Timing = case_when(
      Date > "2025-09-01" ~ "Late",
      Date <= "2025-09-01" ~ "Early",
      TRUE ~ "NA"
    )
  ) %>%
arrange(Plot)

# comparing early to later

# % DC
Cattle_Impact_Repeat %>%
  ggplot(aes(x = Timing, y = Percent_DC, group = Plot, color = HGM_2)) +
  geom_line() +
  theme_bw()

# % Trample
Cattle_Impact_Repeat %>%
  ggplot(aes(x = Timing, y = Percent_Trample, group = Plot, color = HGM_2)) +
  geom_line() +
  theme_bw()

# % Hoof Punch
Cattle_Impact_Repeat %>%
  ggplot(aes(x = Timing, y = Percent_Hoof_Punch, group = Plot, color = HGM_2)) +
  geom_line() +
  theme_bw()

# Manure Count
Cattle_Impact_Repeat %>%
  ggplot(aes(x = Timing, y = Manure_Count, group = Plot, color = HGM_2)) +
  geom_line() +
  theme_bw()


```


CW thoughts/notes of interest -- percent canopy or percent herb vs cattle impacts?


# DC and Hoof punch analyses

```{r dc-punch}

# Framing 1: Is there more likely to be hoof punch in fen areas (based on DC % abundance)?

Cattle_Impact %>% 
  filter(Date < "2025-09-01") %>%
  ggplot(aes(x = Hoof_Punch_Present, y = Percent_DC)) +
  geom_boxplot()



# Framing 2: Is hoof punch percent impact higher where DC is present?
Cattle_Impact %>% 
  mutate(DC_Present = Percent_DC > 0) %>%
  filter(Date < "2025-09-01",
         !is.na(DC_Present)) %>%
  ggplot(aes(x = DC_Present, y = Percent_Hoof_Punch, fill = DC_Present)) +
  geom_boxplot() +
  theme_bw() +
  xlab("D. californica present") +
  ylab("Hoof Punch (% of plot)") +
  scale_fill_manual(values = c('goldenrod','darkgreen')) +
  guides(fill = "none")
ggsave("Figures/DC_Hoof-Punch_plot.pdf", width = 7.5, height = 5.5, units = "in")


# Framing 3a: How does hoof punch % correlate with DC % overall?

Cattle_Impact %>% 
  filter(Date < "2025-09-01") %>%
  ggplot(aes(x = Percent_DC, y = Percent_Hoof_Punch)) +
  geom_point(position = position_jitter()) +
  geom_smooth(method = "lm")


# Framing 3b: How does hoof punch % correlate with DC % where DC is present?
Cattle_Impact %>% 
  filter(Date < "2025-09-01",
         Percent_DC > 0) %>%
  ggplot(aes(x = Percent_DC, y = Percent_Hoof_Punch)) +
  geom_point(position = position_jitter()) +
  geom_smooth(method = "lm")


```

