---
title: "SRWC-seedbank_greenhouse_rm-control"
output:
  word_document: default
  html_document: default
  pdf_document: default
date: "2023-11-13"
---

```{r setup, include=FALSE, echo = FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)

# Color Options:

color.palatte <- c("mediumblue", "darkred") 
fun.palatte <- c("darkolivegreen","darkgoldenrod")
```

## Read in Data

csv file for SRWC seedbank greenhouse study

```{r read-files}

##greenhouse.n <- SRWC_seedbank_greenhouse_2024_02_21_n
  
greenhouse.n <- read.csv(here("data/SRWC-seedbank_greenhouse_2024-02-21_n.csv"), header = TRUE)

greenhouse.n$X <- NULL


```



## Summarize for species richness

summarize by date
```{r summarize-date}

# switch to long format (same data)
greenhouse.long <- greenhouse.n %>% 
  pivot_longer(cols = rf.1.a:control, names_to = "plot", values_to = "count")

# summary by species max count
greenhouse.sum <- greenhouse.long %>% 
  group_by(species, plot) %>% 
  dplyr::summarise(
    count.max = max(count, na.rm = TRUE)) %>%
  filter(count.max > 0)

#View(greenhouse.sum)

# remove species present in control trays
control.species <- greenhouse.sum %>% 
  filter(plot == "control") %>% 
  select(species) %>% 
  unlist()

greenhouse.sum.clean <- greenhouse.sum %>%
  filter(!(species %in% control.species))


# summarize by plots for richness
greenhouse.max.summary <- greenhouse.sum.clean %>%
  group_by(plot) %>%
  dplyr::summarise(
    greenhouse.richness = sum(count.max > 0, na.rm = TRUE)
  )

greenhouse.max.summary


```